### ISSUE TITLE
Custom CPX path

### ISSUE THREAD

**Issue by xdelatour** [freemint/cops#2]
Hi,
I want to change default path for cpx. The new path is stored in cops.inf but when I launch cops.app again, the default path C:\CPX is restored.

My config: Aranym-jit (appimage) + latest snapshot (freemint-1-19-be6) + HostFS with case-sensitive enabled

**Comment by DavidGZ** [comment]
I can't replicate this behaviour. For me the path is changed in the application and in cops.inf. With aranym my configuration file is saved in the disk image so HostFS is not involved, may be this is the reason for the difference between our results?

**Comment by xdelatour** [comment]
It's my fault, after downloading the latest snapshot, I changed the paths in mint.cnf and made a typo. cops could not save its config file in $HOME directory. My apologies!
