### ISSUE TITLE
Icon in the "About" dialog is messed up

### ISSUE THREAD

**Issue by DavidGZ** [freemint/cops#4]
Cops icon in the "About" dialog is all scrambled. Tested with  Aranym+fvdi (32 bit color) and CT60+NVDI (4 bit - 16 colors) 

![cops](https://user-images.githubusercontent.com/25328996/80907772-e9892700-8d19-11ea-9be9-22d294cafe7f.jpg)

**Comment by th-otto** [comment]
Damn. Seems that using coloricons from compiled-in resources does not work on XaAES, they are only transformed by rsrc_load. Have to check how MagiC handles that case, but for now i've added back in the check that i removed in one of the previous commits.
