### ISSUE TITLE
Log file created when COPS is run on EmuTOS

### ISSUE THREAD

**Issue by DavidGZ** [freemint/cops#5]
A log file named "ldg-cpx.log" is created in COPS directory when the application is run on EmuTOS. I haven't seen it on MiNT only EmuTOS. I guess this has beeen left from the development stage.

**Comment by th-otto** [comment]
Hm, this is definitely not created by COPS itself. Could it be that this is from one of your cpx modules?

**Comment by DavidGZ** [comment]
I think the log file comes from one of the CPX not from COPS. Let's close this.

**Comment by DavidGZ** [comment]
:-) We've posted at the same time
